networks:
  dev:




services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - dev
  
  backend:
    build:
      context: ./PythonProject
    networks:
      - dev
    depends_on:
      - datab
    
    

  frontend:
    build:
      context: ./states
    networks:
      - dev
  datab:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: states    
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./sql_init/table_comms.sql:/docker-entrypoint-initdb.d/table_comms.sql
    # network_mode: 'host'
    networks:
      - dev
    
    
  
 