networks:
  dev:




services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - '.\nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - dev
  
  backend:
    build:
      context: ./PythonProject
    
    networks:
      - dev
    depends_on:

  frontend:
    build:
      context: ./states
    networks:
      - dev
    
  
  #database:
    #image: postgres:17
    #ports:
     # - "5432:5432"
    #networks:
    #  - dev
    #environment:
    #  POSTGRES_USER: postgres
    #  POSTGRES_PASSWORD: 1234
    #  POSTGRES_DB: states
   # volumes:
   #  - postgres_data:/var/lib/postgresql/data
    #  - ./init_db:/docker-entrypoint-initdb.d
#volumes:
 # postgres_data:  